-- MySQL Script generated by MySQL Workbench
-- vie 20 nov 2015 13:02:43 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uc` ;

-- -----------------------------------------------------
-- Schema uc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `uc` ;

-- -----------------------------------------------------
-- Table `uc`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_usuario` (
  `id_tipo_us` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_us` VARCHAR(35) NOT NULL COMMENT '',
  `tipo_us_nivel` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_us`)  COMMENT '',
  UNIQUE INDEX `tipo_usuario_UNIQUE` (`tipo_us` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `uc`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tipo_us` INT NOT NULL COMMENT '',
  `us_nom` VARCHAR(25) NOT NULL COMMENT '',
  `us_apat` VARCHAR(25) NOT NULL COMMENT '',
  `us_amat` VARCHAR(25) NOT NULL COMMENT '',
  `us_user` VARCHAR(15) NOT NULL COMMENT '',
  `us_password` VARCHAR(32) NOT NULL COMMENT '',
  `us_email` VARCHAR(45) NULL COMMENT '',
  `us_cel` VARCHAR(25) NULL COMMENT '',
  `us_nivel` INT NOT NULL COMMENT '',
  `us_activo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC)  COMMENT '',
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_us` ASC)  COMMENT '',
  INDEX `us_nivel` (`us_nivel` ASC)  COMMENT '',
  INDEX `us_activo` (`us_activo` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_us`)
    REFERENCES `uc`.`tipo_usuario` (`id_tipo_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`solicitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`solicitante` ;

CREATE TABLE IF NOT EXISTS `uc`.`solicitante` (
  `id_solicitante` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `sol_nom` VARCHAR(25) NOT NULL COMMENT '',
  `sol_apat` VARCHAR(25) NOT NULL COMMENT '',
  `sol_amat` VARCHAR(25) NOT NULL COMMENT '',
  PRIMARY KEY (`id_solicitante`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`tipo_soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_soporte` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_soporte` (
  `id_tiposop` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_soporte` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tiposop`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`soporte` ;

CREATE TABLE IF NOT EXISTS `uc`.`soporte` (
  `id_soporte` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_solicitante` BIGINT NOT NULL COMMENT '',
  `sop_fecha_creacion` DATETIME NOT NULL COMMENT '',
  `sop_fecha_realizacion` DATETIME NOT NULL COMMENT '',
  `sop_fecha_completado` DATETIME NOT NULL COMMENT '',
  `sop_inv` VARCHAR(35) NULL COMMENT '',
  `sop_problema` TEXT NULL COMMENT '',
  `sop_compartido` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id_soporte`)  COMMENT '',
  FULLTEXT INDEX `sop_busqueda` (`sop_problema` ASC)  COMMENT '',
  INDEX `fk_soporte_solicitante2_idx` (`id_solicitante` ASC)  COMMENT '',
  INDEX `sop_completado` (`sop_fecha_completado` ASC)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `uc`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`actividad` ;

CREATE TABLE IF NOT EXISTS `uc`.`actividad` (
  `id_actividad` BIGINT NOT NULL COMMENT '',
  `id_soporte` BIGINT NOT NULL COMMENT '',
  `id_tipo_actividad` INT NOT NULL COMMENT '',
  `act_fecha` DATETIME NOT NULL COMMENT '',
  `act_actividad` TEXT NULL COMMENT '',
  `act_tiempo` INT NOT NULL DEFAULT 0 COMMENT 'minutos',
  PRIMARY KEY (`id_actividad`)  COMMENT '',
  INDEX `fk_actividad_soporte2_idx` (`id_soporte` ASC)  COMMENT '',
  FULLTEXT INDEX `act_busqueda` (`act_actividad` ASC)  COMMENT '',
  INDEX `fk_actividad_tipo_actividad1_idx` (`id_tipo_actividad` ASC)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `uc`.`hashtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`hashtags` ;

CREATE TABLE IF NOT EXISTS `uc`.`hashtags` (
  `id_hashtags` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tiposop` INT NOT NULL COMMENT '',
  `hashtags` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_hashtags`)  COMMENT '',
  INDEX `fk_hashtags_tipo_soporte1_idx` (`id_tiposop` ASC)  COMMENT '',
  CONSTRAINT `fk_hashtags_tipo_soporte1`
    FOREIGN KEY (`id_tiposop`)
    REFERENCES `uc`.`tipo_soporte` (`id_tiposop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`pertenece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`pertenece` ;

CREATE TABLE IF NOT EXISTS `uc`.`pertenece` (
  `id_usuario_de` INT NOT NULL COMMENT '',
  `id_usuario_para` INT NOT NULL COMMENT '',
  `id_soporte` BIGINT NOT NULL COMMENT '',
  `id_tipo_per` INT NOT NULL COMMENT '',
  `id_status` INT NOT NULL COMMENT '',
  INDEX `fk_pertenece_usuario3_idx` (`id_usuario_de` ASC)  COMMENT '',
  INDEX `fk_pertenece_usuario4_idx` (`id_usuario_para` ASC)  COMMENT '',
  INDEX `fk_pertenece_soporte2_idx` (`id_soporte` ASC)  COMMENT '',
  PRIMARY KEY (`id_usuario_para`, `id_soporte`)  COMMENT '',
  INDEX `fk_pertenece_tipo_pertenencia1_idx` (`id_tipo_per` ASC)  COMMENT '',
  INDEX `fk_pertenece_status1_idx` (`id_status` ASC)  COMMENT '',
  CONSTRAINT `fk_pertenece_usuario3`
    FOREIGN KEY (`id_usuario_de`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_usuario4`
    FOREIGN KEY (`id_usuario_para`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_soporte2`
    FOREIGN KEY (`id_soporte`)
    REFERENCES `uc`.`soporte` (`id_soporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_tipo_pertenencia1`
    FOREIGN KEY (`id_tipo_per`)
    REFERENCES `uc`.`tipo_pertenencia` (`id_tipo_per`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `uc`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`realizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`realizado` ;

CREATE TABLE IF NOT EXISTS `uc`.`realizado` (
  `id_usuario` INT NOT NULL COMMENT '',
  `id_actividad` BIGINT NOT NULL COMMENT '',
  `real_creador` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  INDEX `fk_realizado_usuario2_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_realizado_actividad2_idx` (`id_actividad` ASC)  COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_actividad`)  COMMENT '',
  CONSTRAINT `fk_realizado_usuario2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_realizado_actividad2`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `uc`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_usuario` (
  `id_tipo_us` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_us` VARCHAR(35) NOT NULL COMMENT '',
  `tipo_us_nivel` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_us`)  COMMENT '',
  UNIQUE INDEX `tipo_usuario_UNIQUE` (`tipo_us` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `uc`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tipo_us` INT NOT NULL COMMENT '',
  `us_nom` VARCHAR(25) NOT NULL COMMENT '',
  `us_apat` VARCHAR(25) NOT NULL COMMENT '',
  `us_amat` VARCHAR(25) NOT NULL COMMENT '',
  `us_user` VARCHAR(15) NOT NULL COMMENT '',
  `us_password` VARCHAR(32) NOT NULL COMMENT '',
  `us_email` VARCHAR(45) NULL COMMENT '',
  `us_cel` VARCHAR(25) NULL COMMENT '',
  `us_nivel` INT NOT NULL COMMENT '',
  `us_activo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC)  COMMENT '',
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_us` ASC)  COMMENT '',
  INDEX `us_nivel` (`us_nivel` ASC)  COMMENT '',
  INDEX `us_activo` (`us_activo` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_us`)
    REFERENCES `uc`.`tipo_usuario` (`id_tipo_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`solicitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`solicitante` ;

CREATE TABLE IF NOT EXISTS `uc`.`solicitante` (
  `id_solicitante` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `sol_nom` VARCHAR(25) NOT NULL COMMENT '',
  `sol_apat` VARCHAR(25) NOT NULL COMMENT '',
  `sol_amat` VARCHAR(25) NOT NULL COMMENT '',
  PRIMARY KEY (`id_solicitante`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`soporte` ;

CREATE TABLE IF NOT EXISTS `uc`.`soporte` (
  `id_soporte` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_solicitante` BIGINT NOT NULL COMMENT '',
  `sop_fecha_creacion` DATETIME NOT NULL COMMENT '',
  `sop_fecha_realizacion` DATETIME NOT NULL COMMENT '',
  `sop_fecha_completado` DATETIME NOT NULL COMMENT '',
  `sop_inv` VARCHAR(35) NULL COMMENT '',
  `sop_problema` TEXT NULL COMMENT '',
  `sop_compartido` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id_soporte`)  COMMENT '',
  FULLTEXT INDEX `sop_busqueda` (`sop_problema` ASC)  COMMENT '',
  INDEX `fk_soporte_solicitante2_idx` (`id_solicitante` ASC)  COMMENT '',
  INDEX `sop_completado` (`sop_fecha_completado` ASC)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `uc`.`tipo_pertenencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_pertenencia` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_pertenencia` (
  `id_tipo_per` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_per` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_per`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`status` ;

CREATE TABLE IF NOT EXISTS `uc`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_status`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`pertenece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`pertenece` ;

CREATE TABLE IF NOT EXISTS `uc`.`pertenece` (
  `id_usuario_de` INT NOT NULL COMMENT '',
  `id_usuario_para` INT NOT NULL COMMENT '',
  `id_soporte` BIGINT NOT NULL COMMENT '',
  `id_tipo_per` INT NOT NULL COMMENT '',
  `id_status` INT NOT NULL COMMENT '',
  INDEX `fk_pertenece_usuario3_idx` (`id_usuario_de` ASC)  COMMENT '',
  INDEX `fk_pertenece_usuario4_idx` (`id_usuario_para` ASC)  COMMENT '',
  INDEX `fk_pertenece_soporte2_idx` (`id_soporte` ASC)  COMMENT '',
  PRIMARY KEY (`id_usuario_para`, `id_soporte`)  COMMENT '',
  INDEX `fk_pertenece_tipo_pertenencia1_idx` (`id_tipo_per` ASC)  COMMENT '',
  INDEX `fk_pertenece_status1_idx` (`id_status` ASC)  COMMENT '',
  CONSTRAINT `fk_pertenece_usuario3`
    FOREIGN KEY (`id_usuario_de`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_usuario4`
    FOREIGN KEY (`id_usuario_para`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_soporte2`
    FOREIGN KEY (`id_soporte`)
    REFERENCES `uc`.`soporte` (`id_soporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_tipo_pertenencia1`
    FOREIGN KEY (`id_tipo_per`)
    REFERENCES `uc`.`tipo_pertenencia` (`id_tipo_per`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertenece_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `uc`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`tipo_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_actividad` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_actividad` (
  `id_tipo_actividad` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_actividad` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_actividad`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`actividad` ;

CREATE TABLE IF NOT EXISTS `uc`.`actividad` (
  `id_actividad` BIGINT NOT NULL COMMENT '',
  `id_soporte` BIGINT NOT NULL COMMENT '',
  `id_tipo_actividad` INT NOT NULL COMMENT '',
  `act_fecha` DATETIME NOT NULL COMMENT '',
  `act_actividad` TEXT NULL COMMENT '',
  `act_tiempo` INT NOT NULL DEFAULT 0 COMMENT 'minutos',
  PRIMARY KEY (`id_actividad`)  COMMENT '',
  INDEX `fk_actividad_soporte2_idx` (`id_soporte` ASC)  COMMENT '',
  FULLTEXT INDEX `act_busqueda` (`act_actividad` ASC)  COMMENT '',
  INDEX `fk_actividad_tipo_actividad1_idx` (`id_tipo_actividad` ASC)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `uc`.`realizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`realizado` ;

CREATE TABLE IF NOT EXISTS `uc`.`realizado` (
  `id_usuario` INT NOT NULL COMMENT '',
  `id_actividad` BIGINT NOT NULL COMMENT '',
  `real_creador` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  INDEX `fk_realizado_usuario2_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_realizado_actividad2_idx` (`id_actividad` ASC)  COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_actividad`)  COMMENT '',
  CONSTRAINT `fk_realizado_usuario2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_realizado_actividad2`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `uc`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`hashtag` ;

CREATE TABLE IF NOT EXISTS `uc`.`hashtag` (
  `id_hashtag` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tipo_actividad` INT NOT NULL COMMENT '',
  `hashtag` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_hashtag`)  COMMENT '',
  INDEX `fk_hashtag_tipo_actividad1_idx` (`id_tipo_actividad` ASC)  COMMENT '',
  UNIQUE INDEX `hashtag_UNIQUE` (`hashtag` ASC)  COMMENT '',
  CONSTRAINT `fk_hashtag_tipo_actividad1`
    FOREIGN KEY (`id_tipo_actividad`)
    REFERENCES `uc`.`tipo_actividad` (`id_tipo_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`tipo_historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`tipo_historial` ;

CREATE TABLE IF NOT EXISTS `uc`.`tipo_historial` (
  `id_tipo_hist` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_historial` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_hist`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`historial` ;

CREATE TABLE IF NOT EXISTS `uc`.`historial` (
  `id_historial` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_tipo_hist` INT NOT NULL COMMENT '',
  `hist_fecha` DATETIME NOT NULL COMMENT '',
  `hist_ids` VARCHAR(31) NOT NULL COMMENT '',
  PRIMARY KEY (`id_historial`)  COMMENT '',
  INDEX `fk_historial_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_historial_tipo_historial1_idx` (`id_tipo_hist` ASC)  COMMENT '',
  CONSTRAINT `fk_historial_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `uc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_tipo_historial1`
    FOREIGN KEY (`id_tipo_hist`)
    REFERENCES `uc`.`tipo_historial` (`id_tipo_hist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uc`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uc`.`test` ;

CREATE TABLE IF NOT EXISTS `uc`.`test` (
  `idtest` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `testcol1` VARCHAR(45) NOT NULL COMMENT '',
  `testcol2` VARCHAR(45) NOT NULL COMMENT '',
  `testcol3` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idtest`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `uc`.`tipo_pertenencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `uc`;
INSERT INTO `uc`.`tipo_pertenencia` (`id_tipo_per`, `tipo_per`) VALUES (1, 'Creado');
INSERT INTO `uc`.`tipo_pertenencia` (`id_tipo_per`, `tipo_per`) VALUES (2, 'Supervisado');
INSERT INTO `uc`.`tipo_pertenencia` (`id_tipo_per`, `tipo_per`) VALUES (3, 'Asignado');
INSERT INTO `uc`.`tipo_pertenencia` (`id_tipo_per`, `tipo_per`) VALUES (4, 'Compartido');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uc`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `uc`;
INSERT INTO `uc`.`status` (`id_status`, `status`) VALUES (1, 'Pendiente');
INSERT INTO `uc`.`status` (`id_status`, `status`) VALUES (2, 'Realizando');
INSERT INTO `uc`.`status` (`id_status`, `status`) VALUES (3, 'Completado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uc`.`tipo_historial`
-- -----------------------------------------------------
START TRANSACTION;
USE `uc`;
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (1, 'Soporte creado');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (2, 'Soporte modificado');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (3, 'Soporte eliminado');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (4, 'Pertenencia creada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (5, 'Pertenencia modificada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (6, 'Pertenencia eliminada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (7, 'Actividad creada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (8, 'Actividad modificada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (9, 'Actividad eliminada');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (10, 'Usuario vinculado a actividad');
INSERT INTO `uc`.`tipo_historial` (`id_tipo_hist`, `tipo_historial`) VALUES (11, 'Usuario desvinculado de actividad');

COMMIT;

